### PR TITLE
Whitelisting options

### PR DESCRIPTION
**Pull request by nobodysu**
Link the mitigations maybe?

### CODE REVIEW

**Comment by nobodysu** [comment]
`fonts.google.com` could be unnecessary. Maybe it's just a web front.

**Comment by Zig-03** [comment]
Why is there a need for whitelisting fonts.googleapis.com? I have never experienced any issues when blocking fonts.googleapis.com, and usually there's always a fallback font.

**Comment by nobodysu** [comment]
I'm having different experience with `fonts.googleapis.com` on `forum.xda-developers.com` right now. 

Again, it's an option. User should know about consequences - on some sites fallback differences could be crucial.

**Comment by PoorPocketsMcNewHold** [comment]
Capture d'écran de 2019-07-05 19-05-59
As you can see, I´m not having any particuliar issues while using it. Take note that i also block it trough DNS.
As blocking the external fonts domains of a website seems to be pretty self-explanatory, I don’t think we will precise that this could (And will) break some websites.

**Comment by nobodysu** [comment]
If you say so. But what about captcha and Gapis? People will wonder why half of the web is not working and will stop using the repo.

**Pull request closed without merging**
