### PR TITLE
Here is my blocklist, hope you add these (or some)!

### PR DESCRIPTION
**Pull request by scoobydom0**
Since things get bigger, I thought of dividing the list into several categories:
[  + means new category
[  = meaning a category already present
[  - means category no longer necessary
(I used the maiusc to make it more readable)

(+) GENERAL SITES, improved
(+) GOOGLE PRODUCTS, added some (such as waze, hangouts, hire...)
(+) GOOGLE DOMAINS, added some
(=) DOUBLECLICK, added some
(=) GOOGLE ANALYTICS (I haven't touched it)
(=) GOOGLE FONTS (I haven't touched it)
(- ) GOOGLE PLAY (I moved the domains in Google Products)
(=) YOUTUBE, improved
(=) GOOGLE DOCS (I haven't touched it)
(=) FIREBASE (I haven't touched it)
(+) SHORT LINKS
(+) PROXIES (strange domains)
(+) OTHER - YOUTUBE (strange domains)
(+) OTHER - YOUEUBE (strance domains)

Note: Domains (of every category) are all in alphabetical order.
Note: Another note is that GitHub is saying: "Showing with 1,990 additions and 550 deletions.",
but I have only added domains, the others have simply been moved in the categories above.
If you find some domains (especially the ones at the bottom), please tell me, as I don't have much
knowledge in networking and I have no idea whether they are really useful or not.
EDIT: I forgot to say: I entered "0.0.0.0 recaptcha.google.com" in the list. (not sure if it's ok).
(Sorry for my english)
EDIT2: (Use the lase one, which is the 9th from the top now)

### CODE REVIEW

**Comment by PoorPocketsMcNewHold** [comment]
This seems to be fine. I'm not sure however of the revamped Read.me as you've modified it in your own fork, despite i surely like the regex, warning with YouTube, and the domains whitelist. I'll let the final decision on that to nickspaargaren as it's a pretty important addition.

**Comment by nickspaargaren** [comment]
I think I did merge your changes correctly, can you double check? Thank you so much!

**Comment by scoobydom0** [comment]
> This seems to be fine. I'm not sure however of the revamped Read.me as you've modified it in your own fork, despite i surely like the regex, warning with YouTube, and the domains whitelist. I'll let the final decision on that to nickspaargaren as it's a pretty important addition.

Right, I agree! You should change the last part of the readme since this isn't a fork :)

**Comment by nickspaargaren** [comment]
Ahah, you're absolutely right. I'll definitely change that. I gave you all permissions to edit the master so if you want you can change anything you want and help build the list with us.

**Comment by scoobydom0** [comment]
Thx!

**Pull request merged**
